language: node_js
node_js:
  - "node"
  - "iojs"

notifications:
  slack: polyglotted:oI752wOHgUY3xWHyCqXRhLs3

before_install:
  - npm i -g codeclimate-test-reporter
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_script:
  - CODECLIMATE_REPO_TOKEN=2d9df86edf2ee6f922b030c74e1d568f91136913562826359d958db6be0e73ad codeclimate < report/jasmine-coverage/lcov.info
